# Generated by Django 6.0.5 on 2026-05-10 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True)),
                ('draw_date', models.DateTimeField()),
                ('winning_numbers', models.JSONField(blank=True, null=True)),
                ('is_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('is_auto', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround')),
            ],
        ),
        migrations.CreateModel(
            name='Winnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('prize_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoticket')),
            ],
        ),
    ]
